import Footer from "@/components/footer/Footer";
import Headers from "@/components/headers/Headers";
import MobileMenu from "@/components/headers/MobileMenu";
import NextAuthProvider from "@/context/SessionProvider";
import { ThemeProvider } from "@/context/ThemeProvider";
import UtilityProvider from "@/context/UtilityProvider";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextAuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <UtilityProvider>
              <Headers />
              <MobileMenu />
              {children}
              <Footer />
            </UtilityProvider>
          </ThemeProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
